import type { CmsHomePageContent } from '@workspace/shared';

export const homePageFallback: CmsHomePageContent = {
  slug: 'home',
  title: 'Home',
  headerContent: {
    brandName: 'Furniro',
    brandLogoUrl: 'https://www.figma.com/api/mcp/asset/a5d45715-cb0e-42b3-9dfb-5e2d48f9bbcd',
    navItems: [
      { label: 'Home', href: '/' },
      { label: 'Shop', href: '/shop' },
      { label: 'About', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    actionIcons: [
      {
        name: 'account',
        iconUrl: 'https://www.figma.com/api/mcp/asset/d48bec8e-d570-477a-abb6-1cfa29a81574',
      },
      {
        name: 'search',
        iconUrl: 'https://www.figma.com/api/mcp/asset/b132558e-3c73-496d-aa9a-118bf2e02e29',
      },
      {
        name: 'wishlist',
        iconUrl: 'https://www.figma.com/api/mcp/asset/9efe5ac4-fb39-414b-b9ef-1c6a3bcf58f2',
      },
      {
        name: 'cart',
        iconUrl: 'https://www.figma.com/api/mcp/asset/633a88c0-7bde-4cc0-a02c-d626a79dbffe',
      },
    ],
  },
  heroContent: {
    eyebrow: 'New Arrival',
    title: 'Discover Our\nNew Collection',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis.',
    ctaLabel: 'Buy Now',
    ctaHref: '/shop',
    backgroundImageUrl: 'https://www.figma.com/api/mcp/asset/353218ba-c30c-4038-aa89-ff665667bd8f',
  },
  rangeSectionTitle: 'Browse The Range',
  rangeSectionDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  rangeItems: [
    {
      id: 'dining',
      title: 'Dining',
      imageUrl: 'https://www.figma.com/api/mcp/asset/ef9e844a-9891-4317-9929-be27fd1605c7',
      href: '/shop?category=dining',
    },
    {
      id: 'living',
      title: 'Living',
      imageUrl: 'https://www.figma.com/api/mcp/asset/517af79c-8c30-4970-9ddf-43881b579616',
      href: '/shop?category=living',
    },
    {
      id: 'bedroom',
      title: 'Bedroom',
      imageUrl: 'https://www.figma.com/api/mcp/asset/6c31eeaf-8dd7-4484-aa82-9c55513c3967',
      href: '/shop?category=bedroom',
    },
  ],
  productsSectionTitle: 'Our Products',
  showMoreLabel: 'Show More',
  showMoreHref: '/shop',
  products: [
    {
      id: 'syltherine',
      name: 'Syltherine',
      description: 'Stylish cafe chair',
      imageUrl: 'https://www.figma.com/api/mcp/asset/53ace89d-4ca3-43ef-b22d-d108e294132a',
      href: '/shop/syltherine',
      priceLabel: 'Rp 2.500.000',
      originalPriceLabel: 'Rp 3.500.000',
      badgeLabel: '-30%',
      badgeTone: 'discount',
    },
    {
      id: 'leviosa',
      name: 'Leviosa',
      description: 'Stylish cafe chair',
      imageUrl: 'https://www.figma.com/api/mcp/asset/53ace89d-4ca3-43ef-b22d-d108e294132a',
      href: '/shop/leviosa',
      priceLabel: 'Rp 2.500.000',
      showOverlay: true,
    },
    {
      id: 'lolito',
      name: 'Lolito',
      description: 'Luxury big sofa',
      imageUrl: 'https://www.figma.com/api/mcp/asset/818df21b-b94a-448a-ad27-bd0124cee972',
      href: '/shop/lolito',
      priceLabel: 'Rp 7.000.000',
      originalPriceLabel: 'Rp 14.000.000',
      badgeLabel: '-50%',
      badgeTone: 'discount',
    },
    {
      id: 'respira',
      name: 'Respira',
      description: 'Outdoor bar table and stool',
      imageUrl: 'https://www.figma.com/api/mcp/asset/75078330-41ba-45a4-9f5a-a0652de58344',
      href: '/shop/respira',
      priceLabel: 'Rp 500.000',
      badgeLabel: 'New',
      badgeTone: 'new',
    },
    {
      id: 'grifo',
      name: 'Grifo',
      description: 'Night lamp',
      imageUrl: 'https://www.figma.com/api/mcp/asset/20cdc734-ec12-4a29-a4e2-d02453937509',
      href: '/shop/grifo',
      priceLabel: 'Rp 1.500.000',
    },
    {
      id: 'muggo',
      name: 'Muggo',
      description: 'Small mug',
      imageUrl: 'https://www.figma.com/api/mcp/asset/f6ce1104-62f6-4a7d-946b-b27768504a50',
      href: '/shop/muggo',
      priceLabel: 'Rp 150.000',
      badgeLabel: 'New',
      badgeTone: 'new',
    },
    {
      id: 'pingky',
      name: 'Pingky',
      description: 'Cute bed set',
      imageUrl: 'https://www.figma.com/api/mcp/asset/bc175ccc-20bb-47b1-b3ce-9797949e2283',
      href: '/shop/pingky',
      priceLabel: 'Rp 7.000.000',
      originalPriceLabel: 'Rp 14.000.000',
      badgeLabel: '-50%',
      badgeTone: 'discount',
    },
    {
      id: 'potty',
      name: 'Potty',
      description: 'Minimalist flower pot',
      imageUrl: 'https://www.figma.com/api/mcp/asset/dd4ebdd5-6ada-4268-b429-45269b92a696',
      href: '/shop/potty',
      priceLabel: 'Rp 500.000',
      badgeLabel: 'New',
      badgeTone: 'new',
    },
  ],
  productOverlayActions: [
    {
      id: 'share',
      label: 'Share',
      iconUrl: 'https://www.figma.com/api/mcp/asset/d9b77acb-ea8c-48a7-a3c5-5fa64ea30d7b',
    },
    {
      id: 'compare',
      label: 'Compare',
      iconUrl: 'https://www.figma.com/api/mcp/asset/5d92524f-52da-495d-b53b-f9dbb910e203',
    },
    {
      id: 'like',
      label: 'Like',
      iconUrl: 'https://www.figma.com/api/mcp/asset/3c8e16b2-3de8-4fa7-a7e6-ec025a22ffdd',
    },
  ],
  addToCartLabel: 'Add to cart',
  inspirationContent: {
    title: '50+ Beautiful rooms inspiration',
    description: 'Our designer already made a lot of beautiful prototipe of rooms that inspire you',
    ctaLabel: 'Explore More',
    ctaHref: '/shop',
    activeSlideLabel: '01',
    activeSlideCategory: 'Bed Room',
    activeSlideTitle: 'Inner Peace',
    primaryImageUrl: 'https://www.figma.com/api/mcp/asset/da3077bf-198b-441b-a08e-d95ae3d7749a',
    secondaryImageUrl: 'https://www.figma.com/api/mcp/asset/93ee88df-1311-4826-81a9-d46c27da20a8',
    tertiaryImageUrl: 'https://www.figma.com/api/mcp/asset/03354095-dba1-4045-8c6b-128338667ac0',
    primaryActionIconUrl: 'https://www.figma.com/api/mcp/asset/a913b007-04b9-4d65-9035-0e7c7ae2d4a8',
    navigationIconUrl: 'https://www.figma.com/api/mcp/asset/80a7402f-2c64-4823-9c34-6d9e35772fa3',
  },
  shareContent: {
    subtitle: 'Share your setup with',
    title: '#FuniroFurniture',
    tiles: [
      {
        id: 'left-top',
        imageUrl: 'https://www.figma.com/api/mcp/asset/32818dbe-0667-4374-96cd-56d84ba0d890',
        alt: 'Decor setup 1',
        area: 'left-top',
      },
      {
        id: 'left-middle',
        imageUrl: 'https://www.figma.com/api/mcp/asset/a15f69d8-4f19-4e9a-a8b8-2ae4e5d97786',
        alt: 'Decor setup 2',
        area: 'left-middle',
      },
      {
        id: 'left-bottom',
        imageUrl: 'https://www.figma.com/api/mcp/asset/d423307a-8298-45c5-be50-da7f8c8e78e8',
        alt: 'Decor setup 3',
        area: 'left-bottom',
      },
      {
        id: 'center-top',
        imageUrl: 'https://www.figma.com/api/mcp/asset/99804f66-6146-44c0-951a-27467b1a3c4b',
        alt: 'Decor setup 4',
        area: 'center-top',
      },
      {
        id: 'center-bottom',
        imageUrl: 'https://www.figma.com/api/mcp/asset/2a521924-e556-477a-aa2d-3ca497ddde61',
        alt: 'Decor setup 5',
        area: 'center-bottom',
      },
      {
        id: 'right-top',
        imageUrl: 'https://www.figma.com/api/mcp/asset/88bb6fa8-d1ed-400b-973c-075ab0ac6c77',
        alt: 'Decor setup 6',
        area: 'right-top',
      },
      {
        id: 'right-middle',
        imageUrl: 'https://www.figma.com/api/mcp/asset/f866d1f6-d2d3-42df-984c-60385f90ac9f',
        alt: 'Decor setup 7',
        area: 'right-middle',
      },
      {
        id: 'right-small',
        imageUrl: 'https://www.figma.com/api/mcp/asset/9afbd401-0f8e-4e0b-b461-67d7f4a35956',
        alt: 'Decor setup 8',
        area: 'right-small',
      },
      {
        id: 'far-right',
        imageUrl: 'https://www.figma.com/api/mcp/asset/9972b6d0-d0ba-46e8-a6b2-8bf3092bedf5',
        alt: 'Decor setup 9',
        area: 'far-right',
      },
    ],
  },
  footerContent: {
    address: ['400 University Drive Suite 200 Coral Gables, FL 33134 USA'],
    links: [
      { label: 'Home', href: '/' },
      { label: 'Shop', href: '/shop' },
      { label: 'About', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
    helpLinks: [
      { label: 'Payment Options', href: '/payment-options' },
      { label: 'Returns', href: '/returns' },
      { label: 'Privacy Policies', href: '/privacy' },
    ],
    newsletterPlaceholder: 'Enter Your Email Address',
    newsletterActionLabel: 'SUBSCRIBE',
    copyright: '2023 furino. All rights reverved',
  },
};
