services:
  postgres:
    image: postgres:17-alpine
    container_name: website-cms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: website_cms
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
